
package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AdvisorService", targetNamespace = "http://service/", wsdlLocation = "https://isdemm-advisorui.herokuapp.com/advisorUI?wsdl")
public class AdvisorService
    extends Service
{

    private final static URL ADVISORSERVICE_WSDL_LOCATION;
    private final static WebServiceException ADVISORSERVICE_EXCEPTION;
    private final static QName ADVISORSERVICE_QNAME = new QName("http://service/", "AdvisorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://isdemm-advisorui.herokuapp.com/advisorUI?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADVISORSERVICE_WSDL_LOCATION = url;
        ADVISORSERVICE_EXCEPTION = e;
    }

    public AdvisorService() {
        super(__getWsdlLocation(), ADVISORSERVICE_QNAME);
    }

    public AdvisorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADVISORSERVICE_QNAME, features);
    }

    public AdvisorService(URL wsdlLocation) {
        super(wsdlLocation, ADVISORSERVICE_QNAME);
    }

    public AdvisorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADVISORSERVICE_QNAME, features);
    }

    public AdvisorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdvisorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Advisor
     */
    @WebEndpoint(name = "AdvisorPort")
    public Advisor getAdvisorPort() {
        return super.getPort(new QName("http://service/", "AdvisorPort"), Advisor.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Advisor
     */
    @WebEndpoint(name = "AdvisorPort")
    public Advisor getAdvisorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "AdvisorPort"), Advisor.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADVISORSERVICE_EXCEPTION!= null) {
            throw ADVISORSERVICE_EXCEPTION;
        }
        return ADVISORSERVICE_WSDL_LOCATION;
    }

}
